### ISSUE TITLE
Undiscord is not deleting all messages

### ISSUE THREAD

**Issue by olstice** [victornpb/undiscord#472] opened 2023-03-25 05:28 UTC
### Undiscord Version

2.5.0

### Browser

Firefox

### Extension

Tampermonkey

### Reproduction steps

I went to github searched undiscord the userscript created by you. Selected tampermonkey as my script manager. Than went to greasyfork to install the source code with my script manager. Logged on to discord, selected the trash can icon, selected the author ID, selected the server ID, and selected the channel ID, I pressed deleted, the usual message popped up letting me know exactly how many messages will be deleted. I selected confirm, and began the process of automatically deleting each message, 

### Actual results

until somewhere of halfway performance it stopped with the end report that all messages were deleted even thou they were not.

### Expected results

To complete the task of deleting each message by me

### Bug affects

- [X] DMs
- [X] DMs (group)
- [X] Channels
- [ ] Channel (NSFW)

### Additional information & file uploads

is 2.5.0 the most updated version of now?

**Comment by wingedonezero** [comment] 2023-03-25 08:03
Same issue only deletes a max of 25 now and wont delete anymore even if i refresh the tab.

**Comment by zykoytz** [comment] 2023-03-25 14:03
yeah not working after patch discord :(

**Comment by victornpb** [comment] 2023-03-25 16:01
duplicate of #471

**Closed** 2023-03-25 16:01 UTC

**Comment by olstice** [comment] 2023-03-25 22:42
> duplicate of #471

My apologize i didnt realize you can delete this post!
