### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by juanplayerofc** [victornpb/undiscord#470] opened 2023-03-24 16:00 UTC
### Undiscord Version

v5.2.0

### Browser

111.0.5563.66 (Official Build) (64-bit) (cohort: 111_Win_Cotrol) 

### Extension

Violent Monkey

### Reproduction steps

Just started to delete all my messages

### Actual results

Got this error after deleting 25 messages
[End condition A].	{"running":true,"delCount":0,"failCount":0,"grandTotal":84483,"offset":0,"iterations":1,"_seachResponse":{"total_results":84483,"messages":[],"analytics_id":"869e4e5dfadc87197c4eda4790006df9"},"_messagesToDelete":[],"_skippedMessages":[]

### Expected results

Should delete everything

### Bug affects

- [X] DMs
- [ ] DMs (group)
- [ ] Channels
- [ ] Channel (NSFW)

### Additional information & file uploads

![print12](https://user-images.githubusercontent.com/35781119/227578482-7c2a7bcf-e465-4e78-a8c4-6672c04b1ed7.png)

**Comment by obsidianical** [comment] 2023-03-24 16:35
I'm having the exact same issue, I'd guess discord changed their API in the last few hours, breaking tools like undiscord :/

**Comment by NovemberC** [comment] 2023-03-24 17:15
Can confirm having the same problem. Still was able to delete messages yesterday but now it doesn't work anymore, same error.

**Comment by juanplayerofc** [comment] 2023-03-24 17:48
Same

**Comment by Smithy1998** [comment] 2023-03-24 20:51
Same for me. I tried multiple workarounds but nothing works, glad it's not only me having issues.

**Comment by xenicx** [comment] 2023-03-24 22:44
Occurs with channels also. I found workaround which was setting delete delay to 3000ms and then it would delete more than 25 messages at the time. Sure it is slow but at least you don't have to manually delete them.

**Comment by Klownicle** [comment] 2023-03-25 15:09
> Occurs with channels also. I found workaround which was setting delete delay to 3000ms and then it would delete more than 25 messages at the time. Sure it is slow but at least you don't have to manually delete them.

Although not perfect, it allows more to delete but the problem still occurs.

**Comment by victornpb** [comment] 2023-03-25 16:02
duplicate of #471

**Closed** 2023-03-25 16:02 UTC
